# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"\x07\n\x05\x45mpty\")\n\x0bProductList\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product\"\x1e\n\x0eProductRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\"\x1e\n\x10ProductRequestID\x12\n\n\x02id\x18\x01 \x01(\x05\"e\n\x14ProductCreateRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04slug\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\r\n\x05image\x18\x06 \x01(\t\"x\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04slug\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\r\n\x05image\x18\x06 \x01(\t\x12\x12\n\ndate_added\x18\x07 \x01(\t2\xc7\x01\n\x0eProductService\x12#\n\x0bGetProducts\x12\x06.Empty\x1a\x0c.ProductList\x12)\n\nGetProduct\x12\x0f.ProductRequest\x1a\x08.Product\"\x00\x12\x31\n\x10GetProductWithID\x12\x11.ProductRequestID\x1a\x08.Product\"\x00\x12\x32\n\rCreateProduct\x12\x15.ProductCreateRequest\x1a\x08.Product\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_PRODUCTLIST']._serialized_start=26
  _globals['_PRODUCTLIST']._serialized_end=67
  _globals['_PRODUCTREQUEST']._serialized_start=69
  _globals['_PRODUCTREQUEST']._serialized_end=99
  _globals['_PRODUCTREQUESTID']._serialized_start=101
  _globals['_PRODUCTREQUESTID']._serialized_end=131
  _globals['_PRODUCTCREATEREQUEST']._serialized_start=133
  _globals['_PRODUCTCREATEREQUEST']._serialized_end=234
  _globals['_PRODUCT']._serialized_start=236
  _globals['_PRODUCT']._serialized_end=356
  _globals['_PRODUCTSERVICE']._serialized_start=359
  _globals['_PRODUCTSERVICE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
