# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import review_pb2 as review__pb2


class ReviewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddReview = channel.unary_unary(
                '/ReviewService/AddReview',
                request_serializer=review__pb2.ReviewRequest.SerializeToString,
                response_deserializer=review__pb2.Review.FromString,
                )
        self.GetReviews = channel.unary_unary(
                '/ReviewService/GetReviews',
                request_serializer=review__pb2.GetReviewsRequest.SerializeToString,
                response_deserializer=review__pb2.ReviewsList.FromString,
                )


class ReviewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddReview': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReview,
                    request_deserializer=review__pb2.ReviewRequest.FromString,
                    response_serializer=review__pb2.Review.SerializeToString,
            ),
            'GetReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReviews,
                    request_deserializer=review__pb2.GetReviewsRequest.FromString,
                    response_serializer=review__pb2.ReviewsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReviewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ReviewService/AddReview',
            review__pb2.ReviewRequest.SerializeToString,
            review__pb2.Review.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ReviewService/GetReviews',
            review__pb2.GetReviewsRequest.SerializeToString,
            review__pb2.ReviewsList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
