# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: review.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creview.proto\"Y\n\rReviewRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\'\n\x11GetReviewsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"\'\n\x0bReviewsList\x12\x18\n\x07reviews\x18\x01 \x03(\x0b\x32\x07.Review\"r\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\x0e\n\x06rating\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x12\n\ndate_added\x18\x06 \x01(\t2i\n\rReviewService\x12&\n\tAddReview\x12\x0e.ReviewRequest\x1a\x07.Review\"\x00\x12\x30\n\nGetReviews\x12\x12.GetReviewsRequest\x1a\x0c.ReviewsList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'review_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REVIEWREQUEST']._serialized_start=16
  _globals['_REVIEWREQUEST']._serialized_end=105
  _globals['_GETREVIEWSREQUEST']._serialized_start=107
  _globals['_GETREVIEWSREQUEST']._serialized_end=146
  _globals['_REVIEWSLIST']._serialized_start=148
  _globals['_REVIEWSLIST']._serialized_end=187
  _globals['_REVIEW']._serialized_start=189
  _globals['_REVIEW']._serialized_end=303
  _globals['_REVIEWSERVICE']._serialized_start=305
  _globals['_REVIEWSERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
