# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"Q\n\x0e\x41\x64\x64ItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0b\n\x03qty\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\"\"\n\x0fGetOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\"\n\x0f\x43heckoutRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"!\n\x0eGetCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"#\n\x10GetOrdersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"p\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05items\x18\x02 \x01(\t\x12\x0f\n\x07is_open\x18\x03 \x01(\x08\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x12\n\ndate_added\x18\x05 \x01(\t\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x02\" \n\x0fGetCartResponse\x12\r\n\x05items\x18\x01 \x01(\t\"9\n\x11GetOrdersResponse\x12$\n\x06orders\x18\x01 \x03(\x0b\x32\x14.order.OrderResponse\"=\n\tOrderItem\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x0f\n\x07product\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x32\xbe\x02\n\x0cOrderService\x12\x38\n\x07\x41\x64\x64Item\x12\x15.order.AddItemRequest\x1a\x14.order.OrderResponse\"\x00\x12:\n\x08GetOrder\x12\x16.order.GetOrderRequest\x1a\x14.order.OrderResponse\"\x00\x12:\n\x08\x43heckout\x12\x16.order.CheckoutRequest\x1a\x14.order.OrderResponse\"\x00\x12:\n\x07GetCart\x12\x15.order.GetCartRequest\x1a\x16.order.GetCartResponse\"\x00\x12@\n\tGetOrders\x12\x17.order.GetOrdersRequest\x1a\x18.order.GetOrdersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDITEMREQUEST']._serialized_start=22
  _globals['_ADDITEMREQUEST']._serialized_end=103
  _globals['_GETORDERREQUEST']._serialized_start=105
  _globals['_GETORDERREQUEST']._serialized_end=139
  _globals['_CHECKOUTREQUEST']._serialized_start=141
  _globals['_CHECKOUTREQUEST']._serialized_end=175
  _globals['_GETCARTREQUEST']._serialized_start=177
  _globals['_GETCARTREQUEST']._serialized_end=210
  _globals['_GETORDERSREQUEST']._serialized_start=212
  _globals['_GETORDERSREQUEST']._serialized_end=247
  _globals['_ORDERRESPONSE']._serialized_start=249
  _globals['_ORDERRESPONSE']._serialized_end=361
  _globals['_GETCARTRESPONSE']._serialized_start=363
  _globals['_GETCARTRESPONSE']._serialized_end=395
  _globals['_GETORDERSRESPONSE']._serialized_start=397
  _globals['_GETORDERSRESPONSE']._serialized_end=454
  _globals['_ORDERITEM']._serialized_start=456
  _globals['_ORDERITEM']._serialized_end=517
  _globals['_ORDERSERVICE']._serialized_start=520
  _globals['_ORDERSERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
