# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x0b\n\tEmptyUser\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"|\n\x11\x43reateUserRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\r\n\x05photo\x18\x06 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x0fUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\"\n\x10UsernameResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x8c\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\r\n\x05photo\x18\x06 \x01(\t\x12\x10\n\x08is_admin\x18\x07 \x01(\x08\x12\x0f\n\x07\x61pi_key\x18\x08 \x01(\t2\xb6\x01\n\x0bUserService\x12%\n\x0bGetUserById\x12\x0f.GetUserRequest\x1a\x05.User\x12\'\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x05.User\x12!\n\tLoginUser\x12\r.LoginRequest\x1a\x05.User\x12\x34\n\rCheckUsername\x12\x10.UsernameRequest\x1a\x11.UsernameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTYUSER']._serialized_start=14
  _globals['_EMPTYUSER']._serialized_end=25
  _globals['_GETUSERREQUEST']._serialized_start=27
  _globals['_GETUSERREQUEST']._serialized_end=55
  _globals['_CREATEUSERREQUEST']._serialized_start=57
  _globals['_CREATEUSERREQUEST']._serialized_end=181
  _globals['_LOGINREQUEST']._serialized_start=183
  _globals['_LOGINREQUEST']._serialized_end=233
  _globals['_USERNAMEREQUEST']._serialized_start=235
  _globals['_USERNAMEREQUEST']._serialized_end=270
  _globals['_USERNAMERESPONSE']._serialized_start=272
  _globals['_USERNAMERESPONSE']._serialized_end=306
  _globals['_USER']._serialized_start=309
  _globals['_USER']._serialized_end=449
  _globals['_USERSERVICE']._serialized_start=452
  _globals['_USERSERVICE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
